# Generated by Django 3.1.7 on 2022-10-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20221005_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsandtypes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
