# Generated by Django 3.1.7 on 2022-10-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20221005_1406'),
        ('cars', '0002_auto_20221004_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='category.modelsandtypes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='category.modelsandtypes'),
        ),
    ]
