# Generated by Django 3.1.7 on 2022-10-05 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20221005_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2022, 10, 5, 14, 47, 18, 508748)),
        ),
    ]
